[tool.poetry]
name = "ece-calculator"
version = "0.1.0"
description = "Calculate Expected Calibration Error (ECE) from model predictions"
readme = "README.md"
authors = ["Kaylee Smith"]
#license = "MIT"
#homepage = "https://github.com/yourusername/ece-calculator"
#repository = "https://github.com/yourusername/ece-calculator"
keywords = ["ECE", "uncertainty", "calibration", "machine learning"]
packages = [{ include = "ece_calculator", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"
scikit-learn = "^1.7.0"
scipy = "^1.12.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
